# Project information
site_name: FTT成果展示
site_url: 
site_author: Fengtingting
site_description: 
theme:
  name: material 
  logo: pics/logo.png
  language: en
  features:
    - navigation.expand #默认展开导航栏
    - navigation.footer #底部导航栏
    - navigation.tabs #顶级索引被作为tab
    - navigation.top   # 返回顶部的按钮 在上滑时出现
    - search.suggest   # 搜索输入一些字母时推荐补全整个单词
    - search.highlight   # 搜索出的文章关键词加入高亮
    - search.share   #搜索分享按钮吧 
    - navigation.tabs.sticky #tab始终可见
    - navigation.tracking #导航栏跟踪
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: yellow
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
extra_css:
  - 'styles/extra.css' # 路径根据实际情况调整
nav:
  - 首页: index.md
  - 产品类别: 
    - 眼镜类: 产品类别/眼镜类.md
    - 瞄镜类: 产品类别/瞄镜类.md
    - 望远镜类: 产品类别/望远镜类.md
    - 配件类: 产品类别/配件类.md
  - 产品详情: 
    - 产品简介: 产品详情/产品简介.md
    - 产品操作指南:
      - 眼镜类: 
        - ADNV-G14P2: 产品详情/产品操作指南/ADNV-G14P2(V1.2)操作指南.md
        - ADNV-G14SE: 产品详情/产品操作指南/ADNV-G14SE操作指南.md
        - ADNV-GF31: 产品详情/产品操作指南/ADNV-GF31操作指南.md
      - 配件类:
        - ADNV-FM2: 产品详情/产品操作指南/ADNV-FM2支架安装说明书.md
        - ADNV-RS2: 产品详情/产品操作指南/ADNV-RS2录制盒使用说明书.md
    - 版本控制: 产品详情/版本控制.md
  - 软件升级指南:
    - 眼镜类: 
        - ADNV-G14P2: 软件升级指南/ADNV-G14P2软件升级指南.md
        - ADNV-G14SE: 软件升级指南/ADNV-G14SE软件升级指南.md
    - 配件类:
        - ADNV-RS2: 软件升级指南/ADNV-RS2录制盒升级指南.md


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - smarty
  - admonition                                      # 注解块支持
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex                             # 数学公式的TeX语法支持
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:                                     # 表情支持
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:                              # 任务清单支持
      custom_checkbox: true
  - pymdownx.tilde
  - meta                                            # 元数据支持
  - attr_list 